### ISSUE TITLE
Twitter logo and banner doesn't display correctly

### ISSUE THREAD

**Issue by KevinYum** [419Labs/starknet-ecosystem.com#168]
Hi there,

I recently submitted a pull request for WIW protocol https://github.com/419Labs/starknet-ecosystem.com/pull/166

However, the twitter logo and banner is not displayed correctly on deployed website.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/2398013/201261200-52b524e7-8bef-459a-9d00-54d371e54f13.png">

I've double checked the twitter link provided in PR and it should be correct. Anyone has some clue?

**Comment by 0xlny** [comment]
Hi @KevinYum 

Thanks for feedback, after adding a project there is a maximum 24h of cache update.

Seems to be ok now :)
