### ISSUE TITLE
Banner not updated for STRKFarm

### ISSUE THREAD

**Issue by web3Gurung** [419Labs/starknet-ecosystem.com#682]
Hey team, it's been 3 days since the PR to add STRKFarm was merged: https://github.com/419Labs/starknet-ecosystem.com/pull/675, but the banner is not updated yet.

I've read the previous issue on the same problem and found out that it takes up to 24 hours for the cache update: https://github.com/419Labs/starknet-ecosystem.com/issues/168

Since it's been more than 72 hours, I am raising this issue to get some clarity on how we can fix this. Let me know if there's anything we can do from our end!

Project link: https://www.starknet-ecosystem.com/projects/0f2ecfe3-1212-4157-9176-aeeb4204294f

Attaching images here:
![image](https://github.com/419Labs/starknet-ecosystem.com/assets/72032538/136a8427-bbb6-4a12-ba4c-efae0047d048)
![image](https://github.com/419Labs/starknet-ecosystem.com/assets/72032538/28d7c9f2-a5ff-408c-8e0a-f00f87906ee3)

**Comment by 0xlny** [comment]
Starknet-db was not synced correctly, fixed now
